project:
  type: website
  output-dir: docs

website:
  title: "Course Title"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Pakillo/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://github.com/Pakillo/quarto-course-website-template/discussions
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

